name: Proof HTML
on:
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cloud:
        - gcp
        environment:
        - dev
        # - stage
        # - prod
        location:
        - us-west2
        - us-east4
    steps:
      - uses: anishathalye/proof-html@v1.1.0
        name: ${{ matrix.cloud }}_${{ matrix.environment }}_${{ matrix.location }}
        with:
          directory: ./
